"""initial schema

Revision ID: 1756ba85c2f8
Revises: 
Create Date: 2026-07-04 09:29:36.459135+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1756ba85c2f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.Column('last_message_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("type IN ('direct','group')", name='ck_conversations_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('conversation_members',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.String(length=32), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.Column('is_muted', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id')
    )
    with op.batch_alter_table('conversation_members', schema=None) as batch_op:
        batch_op.create_index('idx_members_user', ['user_id'], unique=False)

    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.CheckConstraint("status IN ('accepted','pending','blocked')", name='ck_follows_status'),
    sa.ForeignKeyConstraint(['followee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('follower_id', 'followee_id')
    )
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.create_index('idx_follows_followee_status', ['followee_id', 'status'], unique=False)
        batch_op.create_index('idx_follows_follower_status', ['follower_id', 'status'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('ciphertext', sa.LargeBinary(), nullable=False),
    sa.Column('reply_to_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('edited_at', sa.String(length=32), nullable=True),
    sa.Column('deleted_at', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index('idx_messages_conv_time', ['conversation_id', 'created_at'], unique=False)
        batch_op.create_index('idx_messages_sender', ['sender_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.String(length=32), nullable=False),
    sa.Column('revoked_at', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('idx_refresh_tokens_family', ['family_id'], unique=False)
        batch_op.create_index('idx_refresh_tokens_user', ['user_id'], unique=False)

    op.create_table('message_deliveries',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delivered_at', sa.String(length=32), nullable=False),
    sa.Column('read_at', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    with op.batch_alter_table('message_deliveries', schema=None) as batch_op:
        batch_op.create_index('idx_deliveries_user_unread', ['user_id', 'message_id'], unique=False)

    # ### end Alembic commands ###


    # Case-insensitive search indexes. Alembic's autogenerate can't reflect
    # expression-based indexes, so we add them as raw SQL. SQLite supports
    # CREATE INDEX ... ON tbl (LOWER(col)) since 3.9.
    op.execute("CREATE INDEX IF NOT EXISTS idx_users_username_lower ON users (LOWER(username))")
    op.execute("CREATE INDEX IF NOT EXISTS idx_users_email_lower    ON users (LOWER(email))")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message_deliveries', schema=None) as batch_op:
        batch_op.drop_index('idx_deliveries_user_unread')

    op.drop_table('message_deliveries')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('idx_refresh_tokens_user')
        batch_op.drop_index('idx_refresh_tokens_family')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index('idx_messages_sender')
        batch_op.drop_index('idx_messages_conv_time')

    op.drop_table('messages')
    with op.batch_alter_table('follows', schema=None) as batch_op:
        batch_op.drop_index('idx_follows_follower_status')
        batch_op.drop_index('idx_follows_followee_status')

    op.drop_table('follows')
    with op.batch_alter_table('conversation_members', schema=None) as batch_op:
        batch_op.drop_index('idx_members_user')

    op.drop_table('conversation_members')
    op.drop_table('users')
    op.drop_table('conversations')
    # ### end Alembic commands ###


    op.execute("DROP INDEX IF EXISTS idx_users_email_lower")
    op.execute("DROP INDEX IF EXISTS idx_users_username_lower")
